WIP: Room feature
sjnarvaez17/pokedex-app pull request #4
Opened 2022-12-21 03:31 UTC by sjnarvaez17

Room dependency added and creating Pokemon entity.Meanwhile, i search about how to create entity when has an object inside

2022-12-21 03:31 UTC, sjnarvaez17 commented
@hanarvaez

2022-12-21 03:39 UTC, hanarvaez requested changes

2022-12-21 03:39 UTC, hanarvaez commented on app/src/main/java/com/example/pokedexdesafio/domain/entities/PokemonEntity.kt
> +    @PrimaryKey val id: Int?,
A primary key can't be null

2022-12-31 22:04 UTC, closed without merging

2022-12-31 22:04 UTC, hanarvaez commented
closed PR as this is not developed in the right way